### ISSUE TITLE
Extension is being activated if submitted search form contains ".guide"

### ISSUE THREAD

**Issue by amigaosz** [rkidd7952/aguide-viewer#8]
I hope I didn't somehow overlook that this issue has already been reported.

What I noticed: If I enter ".guide" in the search term on duckduckgo.com or Google or actually in any other search form on the site and send the request, the extension is automatically activated. I'm using Firefox 113.0.1 (64-bit) on Linux Mint.

By the way: Great plugin, I've been looking for something like this for a long, long time. Thank you so much for the great work! :)

**Comment by rkidd7952** [comment]
Thank you for the report and the kind words!

I was able to reproduce the issue.  Commit [18de98fe](https://github.com/rkidd7952/aguide-viewer/commit/18de98fe11882abdb463dbb3f07a0ed071bbf892) makes the extension less aggressive about intercepting downloads.  The extension no longer intercepts search terms as you reported.

This will be part of v0.2.

**Comment by rkidd7952** [comment]
[Version 0.2](https://github.com/rkidd7952/aguide-viewer/releases/tag/v0.2) is now available with the fix for this issue.
